#spring:
#  application:
#    name: E-Libarary


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minor_project?createDatabaseIfNotExist=true
    username: root
    password: "your-passord"
  jpa:
     hibernate.ddl-auto: update
     show-sql: true


server:
  port: 8080

custom_property:
      property1: value1
